# Generated by Django 5.2.17 on 2026-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Tempo Limite (Minutos)'),
        ),
    ]
