# Generated by Django 5.2.17 on 2026-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_time_limit_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa / Comentário do Professor'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='É a resposta correta?'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Texto da Alternativa'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Nota Mínima de Aprovação (%)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Aprovado?'),
        ),
    ]
