# Generated by Django 5.2.17 on 2026-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave da Sessão Atual'),
        ),
    ]
