# Generated by Django 5.2.17 on 2026-08-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_current_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código da Conquista'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('icon', models.CharField(default='bi-bell', max_length=50, verbose_name='Ícone')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RG', 'Documento de Identidade (RG/CNH)'), ('CPF', 'CPF'), ('RESIDENCE', 'Comprovante de Residência'), ('ASO', 'ASO / Atestado Médico de Aptidão Física'), ('DIPLOMA', 'Comprovante de Escolaridade')], max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='student_documents/', verbose_name='Arquivo Anexo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado pela Secretaria')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Matrícula',
                'verbose_name_plural': 'Documentos de Matrícula',
            },
        ),
    ]
