services:
  - type: web
    name: sistema-matricula
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: EMAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: SUPABASE_URL
        value: "https://taddgzgbgstttecbvkmc.supabase.co"
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: "matricula-docs"
      # Pooler do Supabase
      - key: DB_HOST
        value: "aws-0-us-east-1.pooler.supabase.com"  # ← MESMO HOST DO POOLER
      - key: DB_PORT
        value: "6543"
      - key: DB_USER
        value: "postgres.taddgzgbgstttecbvkmc"
      - key: DB_PASSWORD
        value: "SenhaMatricula2026!"
      - key: DB_NAME
        value: "postgres"