services:
  - type: web
    name: sistema-matricula
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
        
      # Configuração do Banco de Dados PostgreSQL (Supabase Pooler) em uma única linha
      - key: DATABASE_URL
        value: "postgresql://postgres.taddgzgbgstttecbvkmc:SenhaMatricula2026!@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
        
      # Variáveis do Supabase Storage (Documentos)
      - key: SUPABASE_URL
        value: "https://taddgzgbgstttecbvkmc.supabase.co"
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: "matricula-docs"