# Generated by Django 5.2.17 on 2026-08-06 00:19

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.models.validate_cpf], verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, verbose_name='RG')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('assinatura', models.TextField(blank=True, verbose_name='Assinatura Digital')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('foto', 'Foto 3x4')], max_length=10, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.matricula')),
            ],
        ),
    ]
