# Generated by Django 5.2.17 on 2026-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='assinatura',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aceitou_termos',
            field=models.BooleanField(default=False, verbose_name='Aceitou os termos'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Registro'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='Navegador/Dispositivo'),
        ),
    ]
