# Generated by Django 5.2.17 on 2026-08-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_matricula_assinatura_matricula_aceitou_termos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF')], max_length=10, verbose_name='Tipo'),
        ),
    ]
