# Generated by Django 5.2.17 on 2026-08-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Código de Autenticidade (Hash)')),
                ('qr_code_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do QR Code')),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Válido / Ativo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.coursemodel', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
