# Generated by Django 5.2.17 on 2026-08-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_options_and_more'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='auth_code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Código Hash de Autenticidade'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.coursemodel', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Documento Válido'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do QR Code'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
    ]
