# Generated by Django 5.2.17 on 2026-08-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='code',
            field=models.CharField(default='TEMP_CODE', max_length=50, unique=True, verbose_name='Código de Autenticidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Arquivo PDF do Certificado'),
        ),
    ]
