# Generated by Django 5.2.17 on 2026-08-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_unique_together_certificate_code_and_more'),
        ('courses', '0004_course_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Curso'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='auth_code',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file_path',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code_image',
        ),
    ]
