# Generated by Django 5.2.17 on 2026-08-07 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Curso')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('NR_REGULATORY', 'Norma Regulamentadora (NR)'), ('CIVIL_FIREFIGHTER', 'Bombeiro Civil'), ('LIFEGUARD', 'Guardião de Piscina'), ('FREE_COURSE', 'Curso Livre')], default='FREE_COURSE', max_length=30, verbose_name='Categoria')),
                ('workload_hours', models.PositiveIntegerField(verbose_name='Carga Horária (Horas)')),
                ('min_passing_score', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, max_length=4, verbose_name='Nota Mínima (%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Curso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Módulo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.coursemodel', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Aula')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Vídeo (YouTube)'), ('PDF', 'Apostila / PDF'), ('TEXT', 'Texto / Leitura')], default='VIDEO', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('youtube_video_id', models.CharField(blank=True, help_text='Exemplo: dQw4w9WgXcQ (Apenas o ID da URL)', max_length=100, null=True, verbose_name='ID do Vídeo no YouTube')),
                ('pdf_storage_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho/URL do PDF')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo em Texto')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duração total do vídeo para cálculo de presença.', verbose_name='Duração da Aula (em segundos)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem da Aula')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('COMPLETED', 'Concluída')], default='PENDING', max_length=15, verbose_name='Status da Matrícula')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='courses.coursemodel', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Tempo Assistido (Segundos)')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Último Acesso')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='Aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Progresso do Aluno',
                'verbose_name_plural': 'Progressos dos Alunos',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
