# Generated by Django 5.2.17 on 2026-08-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_course_and_more'),
        ('courses', '0004_course_question_and_more'),
        ('quizzes', '0004_remove_question_quiz_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseModel',
        ),
    ]
